version: 2.1
orbs:
  codecov: codecov/codecov@1.0.5
jobs:
  build:
    docker:
      - image: circleci/node:13.0.1
    steps:
      - add_ssh_keys:
        fingerprints:
          - "05:89:96:d9:c9:90:30:e8:d1:2f:78:d8:2e:83:53:64"
      - checkout
      - restore_cache:
          keys:
            - v0dependencies-{{checksum "package.json"}}
            - v0dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v0dependencies-{{checksum "package.json"}}
      - run: npm test:coverage
      - codecov/upload:
          file: coverage/
